### ISSUE TITLE
Button add ons (so we dont' forget) 

### ISSUE THREAD

**Issue by acchiang** [nwplus/portal#128]
Asked design in slack for these review points: 
https://nwplus-ubc--pr119-buttons-ak9dpwds.web.app/charcuterie
1. size and width: :+1: or :-1: ? if :-1: , could you go into dev tools on the staging site and let me know what css width and padding you would like? the ones on figma are not up to scale (i think it’s a figma issue). lmk if I can help!
2. when focused: try hitting the Tab key to traverse through the buttons, is the focus state ok? this is for accessibility as well
3. when clicked: i’m not sure who designed the ripple effect onclick, but i love it. unfortunately it’s quite a big thing to code, and we are on a really tight time crunch. is it ok to revisit this later? alternatively here and here are some resources i found, if anyone from design has react dev expertise pls teach me how to do it :pray:
4. destructive: not doing these for now (no use case yet) but i’d be happy to add them if anyone has capacity to design them in the hacker app figma!

Basic button functionality is being completed as part of #80

**Comment by ianmah** [comment]
Other issues: nwHacks primary buttons flicker on hover. Also hackcamp buttons flick on hover
Hackcamp primary buttons need to have multiple widths
Hackcamp primary buttons need to be double checked on mobile (height is cut off)
