### ISSUE TITLE
Add categories to sidebar

### ISSUE THREAD

**Issue by kevin-zou** [nwplus/portal#330]
The sidebar on Portal is being reworked to have categories for the links. The categories and their links (in order) are listed below. An arrow `->` means the page exists and is being renamed.

**General**
Quicklinks -> Getting Started
Dashboard -> Home
Schedule
Sponsors

**Tools**
Project Gallery (new)
Submission -> Project Submission
Judging -> Peer Judging
Judging Admin (organizer only)

**Information**
Info Package (new)
Judging (new)
FAQ

The headers should be in a font that is smaller and lighter in the color than the links. If you need design guidance feel free to ask for it in the slack channel!

**Comment by naijwu** [comment]
Is the Judging link under the Information category new? Or would it be the rename of "Judging Admin"?

**Comment by kevin-zou** [comment]
Hmm good question, I think it is but @anneguo3 do you know?

**Comment by kevin-zou** [comment]
Just asked Anne, I'll update the description to match!
