### ISSUE TITLE
Project submission form

### ISSUE THREAD

**Issue by kevin-zou** [nwplus/portal#333]
Update the current submission page to be a fully fledged form that has the following fields:
- Project name (char limited)
- Team members (name + email)
- Short description (char limited)
- Description
- Links*

*There can be a lot of different links (eg. YouTube demo link, deployed link, code, design docs), so could we either:
1) Have a plus icon that makes a new field, and a delete icon that removes a field, or
2) Just have 5 fields from the start (all of them which are not required)

The form should be fully validated as well, using functions from `Validation.js` or making new ones there.

**Comment by anneguo3** [comment]
Note: We also need the ability to select sponsor prizes in this form

**Comment by kevin-zou** [comment]
Ohh good call, thanks for the reminder!
